# C:/T19/JavaProject/mvn_sample_app/k8s/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-guardian-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-guardian
  template:
    metadata:
      labels:
        app: ai-guardian
    spec:
      containers:
      - name: ai-guardian
        image: srigiriraja/ai-guardian:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:               # ✅ Inside the container
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000   # (non-root user id)
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"